apiVersion: apps/v1
kind: Deployment
metadata:
  name: efs-test-deployment
  namespace: default
  labels:
    app: efs-test-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: efs-test-app
  template:
    metadata:
      labels:
        app: efs-test-app
    spec:
      containers:
        - name: efs-test-app
          image: busybox
          command: ["/bin/sh"]
          args: ["-c", "while true; do echo $(date -u) >> /data/out1.txt; sleep 5; done"]
          volumeMounts:
          - name: persistent-storage
            mountPath: /data
          resources:
            requests:
              memory: "0.5G"
              cpu: "0.25"
            limits:
              memory: "0.5G"
              cpu: "0.25"
      volumes:
        - name: persistent-storage
          persistentVolumeClaim:
            claimName: efs-claim
