apiVersion: v1
kind: Service
metadata:
  name: efs-test-service
  namespace: default
  labels:
    app: efs-test-app
spec:
  selector:
    app: efs-test-app
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
